name: cicd

on:
  push:
    branches:
      - 'development'
      - 'master'
      - 'main'
      - 'releases/**'
  pull_request:
    branches:
      - 'development'
      - 'master'
      - 'main'
      - 'releases/**'

jobs:
  test_and_lint:
    name: Unit Testing and Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Docker Compose Run
        run: |
          echo "docker-compose"
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Check Directory
        run: |
          ls -lart

      - name: Terraform Init
        run: terraform -chdir=deploy init -backend=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: '.'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Validate
        run: terraform -chdir=deploy validate -no-color

      - name: Build and Push Image
        run: |
          echo "Build and Push Image "

      - name: Terraform Init
        run: |
          echo "Terraform Init"

      - name: Terraform Plan
        run: |
          echo "Terraform Plan"

      - name: Terraform Apply
        run: |
          echo "Terraform Apply"